#!/bin/sh

# download http://tools.suckless.org/ii/ and `make clean install` to ./us/ prefix

channels='#us'

dir=/home/git/git-bot

trap "" HUP

while true; do
  export IIPASS='AvJFdxEXYXRXuDnXSrTdq6Q38wMTp8'
  $dir/ii/bin/ii -i $dir/irc/ -s localhost -e ssl -f 'git' -n git -k IIPASS &
  iipid="$!"

  sleep 1

  echo '/mode git +B' >$dir/irc/localhost/in
  for ch in $channels ; do
    echo "/j $ch" >$dir/irc/localhost/in
  done

  wait "$iipid"
  sleep 1
done &
