#!/bin/sh

# download http://tools.suckless.org/ii/ and `make clean install` to ./us/ prefix

channels='#us'

dir=/home/git/git-bot

export IIPASS='AvJFdxEXYXRXuDnXSrTdq6Q38wMTp8'
nohup $dir/ii/bin/ii -i $dir/irc/ -s localhost -e ssl -f 'git' -n git -k IIPASS &

nohup sh -c "sleep 10 && printf '/mode git +B\n/j $channels\n' >$dir/irc/localhost/in" &
