#!/bin/sh

# ./connect and call this script from your $REPO.git/hooks/post-receive script
# takes two args: <network> and <channel> (these are ii's args, see ./connect)

die() {
  echo 'fatal:' "$@" >&2
  exit 1
}

[ "$#" -eq 2 ] || die "usage: $0 <network> <channel>"

owndir="$(dirname "$(readlink -f "$0")")"
network="$owndir/irc/$1/in"
channel="$owndir/irc/$1/$2/in"

[ -p "$network" ] || die "$network: not a named pipe; edit $owndir/connect script and reconnect"

[ -p "$channel" ] || {
  echo "git-bot: $1/$2 not yet joined; joining"
  echo "/j $2" >"$network"
  sleep 1
  [ -p "$channel" ] || die "$channel: not a named pipe; edit $owndir/connect script and reconnect"
}

cat | "$owndir/post-receive-irc" >"$channel"
