#!/bin/sh

d="$(dirname "$(readlink -f "$0")")"

ch="$d/irc/localhost/#us"

tail -n0 -f "$ch/out" | while read -r line ; do
  who="$(echo "$line" | sed -re 's/^[^<]+<([^>]+).*$/\1/g')" || continue
  msg="$(echo "$line" | sed -re 's/^[^>]*> //g')"
  "$d/silliness-behav" "$who" "$msg" >"$ch/in"
done
