#!/usr/bin/perl

use strict;
use warnings;
use utf8;

binmode(STDIN, ":utf8");
binmode(STDERR, ":utf8");
binmode(STDOUT, ":utf8");

my @slaps = (
  'activates her slap-o-matic…',
  'beats up ___.',
  'clobbers ___ with an untyped language.',
  'decomposes ___ into several parts using the Banach-Tarski theorem and reassembles them to get two copies of ___!',
  'hits ___ with an assortment of kitchen utensils.',
  'hits ___ with a hammer, so they break into a thousand pieces.',
  'is overcome by a sudden desire to hurt ___.',
  'jabs ___ with a C pointer.',
  'karate-chops ___ into two equally sized halves.',
  'locks up ___ in a Monad.',
  'orders her trained monkeys to punch ___.',
  'places her fist firmly on ___\'s jaw.',
  'pokes ___ in the eye.',
  'pulls ___ through the Evil Mangler.',
  'puts on her slapping gloves, and slaps ___.',
  'secretly deletes ___\'s source code.',
  'slaps ___ with a slab of concrete.',
  "\x02*SMACK*\x0f, \x02*SLAM*\x0f, take that ___!",
  'smacks ___ about with a large trout.',
  'smashes a lamp on ___\'s head.',
  'throws some pointy lambdas at ___.',
  'whistles too.',
  'will count to five…'
);

my $line = <>;
chomp $line;
$line =~ s/^\d\d\d\d-\d\d-\d\d \d\d:\d\d //;

if ($line =~ /^<(.+?)>\s+(.*?)\s*$/) {
  my $who = $1;
  my $msg = $2;

  if ($who =~ /git/i) { }

  elsif ($msg =~ /^[!@]g (.*)$/i) {
    my $q = $1;
    $q =~ s/\s+/+/g;
    $q =~ s/'/%27/g;
    $q =~ s/"/%22/g;
    print "https://www.google.com/search?q=$q\n";
  }

  elsif ($msg =~ /^[!@]h$/i) {
    print "$who, hilight!\n";
  }

  elsif ($msg =~ /^[!@]slap\s+(.*?)\s*$/i) {
    my $t = $1;
    my $r = $slaps[rand @slaps];
    $r =~ s/___/$t/g;
    print "\x01ACTION $r\x01\n";
  }

}
